spring:
  application:
    name: turbine

server:
  port: 9011

management:
  port: 9021

turbine:
  instanceUrlSuffix: /hystrix.stream
#  aggregator:
#    clusterConfig: default   # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  appConfig: producer-user , gateway, producer-contract, producer-schedule  # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")
  combine-host-port: true