server:
  port: 8085

# 需要指明spring.application.name
# 这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: producer-user

token:
  enable: true

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: hystrix.stream, health
