version: "3"
services:

  pal-server:
    image: golang:1.8
    build: ./pal-server
    image: pal-server
    ports:
      - "9090:9090"
    volumes:
      - /home/docker/point_and_line/pal-server:/home
    depends_on:
      - "photio-mysql"
    networks:
      - photio

  pal-mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3308:3306"
    volumes:
      - /home/docker/photio/photio-mysql/init_sql:/docker-entrypoint-initdb.d
      - /home/docker/photio/photio-mysql/data/log/:/var/log/
      - /home/docker/photio/photio-mysql/data/mysqld/:/var/run/mysqld/
      - /home/docker/photio/photio-mysql/data/mysql:/var/lib/mysql
      - /home/docker/photio/photio-mysql/my.cnf:/etc/my.cnf
    networks:
      - photio

networks:
  photio:
