use mysql;
grant all privileges on *.* to [your_mysql_name]@'%' identified by "your_mysql_pwd";
flush privileges;

-- MySQL Script generated by MySQL Workbench
-- 09/03/18 15:57:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema photio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `photio` ;

-- -----------------------------------------------------
-- Schema photio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `photio` DEFAULT CHARACTER SET utf8mb4 ;
USE `photio` ;

-- -----------------------------------------------------
-- Table `photio`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photio`.`user` ;

CREATE TABLE IF NOT EXISTS `photio`.`user` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT 'id',
  `account` VARCHAR(32) NOT NULL COMMENT 'account',
  `phone` VARCHAR(16) NOT NULL COMMENT 'mobile phone number',
  `pwd` VARCHAR(256) NOT NULL COMMENT 'SHA pwd',
  `user_name` VARCHAR(64) NULL COMMENT 'user nick name',
  `type` TINYINT UNSIGNED NOT NULL COMMENT '0 - admin; 1 - model; 2 - photographer;',
  `state` TINYINT NOT NULL COMMENT '0 - deleted; 1 - activied',
  `score` BIGINT UNSIGNED NOT NULL COMMENT 'score of user',
  `create_date` DATETIME NOT NULL COMMENT 'create time',
  `creator_id` BIGINT NULL COMMENT 'creator user id',
  `update_date` DATETIME NOT NULL COMMENT 'update time',
  `updater_id` BIGINT NULL COMMENT 'updater user id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'user';

CREATE UNIQUE INDEX `account_UNIQUE` ON `photio`.`user` (`account` ASC);

CREATE UNIQUE INDEX `phone_UNIQUE` ON `photio`.`user` (`phone` ASC);


-- -----------------------------------------------------
-- Table `photio`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photio`.`schedule` ;

CREATE TABLE IF NOT EXISTS `photio`.`schedule` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT 'id',
  `user_id` BIGINT NOT NULL,
  `free_date` DATETIME NOT NULL,
  `is_scheduled` TINYINT NOT NULL,
  `tags` TEXT NULL COMMENT '{\"\", \"\"}',
  `create_date` DATETIME NOT NULL COMMENT 'create time',
  `creator_id` BIGINT NULL COMMENT 'creator user id',
  `update_date` DATETIME NOT NULL COMMENT 'update time',
  `updater_id` BIGINT NULL COMMENT 'updater user id')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'schedule';


-- -----------------------------------------------------
-- Table `photio`.`invitation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photio`.`invitation` ;

CREATE TABLE IF NOT EXISTS `photio`.`invitation` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT 'id',
  `invitor_id` BIGINT NOT NULL,
  `target_user_id` BIGINT NOT NULL,
  `target_schedule_id` BIGINT NOT NULL COMMENT '被邀请者计划',
  `scheduled_date` DATETIME NOT NULL,
  `state` TINYINT NOT NULL COMMENT '0 - idle; 1 - accepted; 2 - finished; 3 - channel; 4 - rejected;',
  `create_date` DATETIME NOT NULL COMMENT 'create time',
  `creator_id` BIGINT NULL COMMENT 'creator user id',
  `update_date` DATETIME NOT NULL COMMENT 'update time',
  `updater_id` BIGINT NULL COMMENT 'updater user id')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `photio`.`evaluation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photio`.`evaluation` ;

CREATE TABLE IF NOT EXISTS `photio`.`evaluation` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT 'id',
  `user_id` BIGINT NOT NULL,
  `evatuate_user_id` BIGINT NOT NULL,
  `score` INT UNSIGNED NOT NULL,
  `msg` TEXT NULL,
  `create_date` DATETIME NOT NULL COMMENT 'create time',
  `creator_id` BIGINT NULL COMMENT 'creator user id',
  `update_date` DATETIME NOT NULL COMMENT 'update time',
  `updater_id` BIGINT NULL COMMENT 'updater user id')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
